apiVersion: apps/v1
kind: Deployment
metadata:
  name: angular-app
  namespace: hypertheory
spec:
  selector:
    matchLabels:
      app: angular-app
  template:
    metadata:
      labels:
        app: angular-app
    spec:
      containers:
      - name: angular-app
        image: jeffrygonzalez/angular-app-jun-2023:v0.1
        resources:         
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
